### ISSUE TITLE
GraphQL subscriptions

### ISSUE THREAD

**Issue by alexander-mart** [jycouet/kitql#100]
Do you have plan to implement graphql subscriptions for real-time?

**Comment by jycouet** [comment]
Yes, I'm planning to have this soon in the client.

**Comment by gevera** [comment]
This feature will make KitQL it even better!

**Comment by frederikhors** [comment]
I'm reading https://www.the-guild.dev/blog/subscriptions-and-live-queries-real-time-with-graphql. It's interesting!

**Comment by jycouet** [comment]
It's the direction I'm going to! 👍

**Comment by gevera** [comment]
> It's the direction I'm going to! +1

Is there a working branch or repo ?  How can we help?

**Comment by jycouet** [comment]
It took time, but it finally happened!

Check out the [Announcements here](https://github.com/jycouet/kitql/discussions/156#discussioncomment-3080343)

---

Yes, GraphQL Subscription is in 🎉
