### ISSUE TITLE
queryLoad does not use the provided variables

### ISSUE THREAD

**Issue by gregoryforel** [jycouet/kitql#109]
`@kitql/all-in version: 0.6.3`

**Problem**: `queryLoad` does not load the data when the query expects a variable. I suspect the variable is _not_ used even if provided. `query` works however. Also, using `KitQLInfo`, variables are `null`.

I have a simple `my-query.graphql` file, and generate all the types and stores with codegen as per your tutorial.

```graphql
query GetResumeById($id: uuid!) {
	resumes_by_pk(id: $id) {
		id
		name
	}
}
```

```svelte
<script context="module" lang="ts">
	import { browser, dev } from '$app/env'
	import { KQL_GetResumeById } from '$lib/data-access/graphql/_kitql/graphqlStores'
	
        export const hydrate = dev
	export const router = browser
	export const prerender = true
        
        // Does not work
	export async function load({ fetch }) {
		await KQL_GetResumeById.queryLoad({
			fetch,
                        variables: { id: 'fa69f955-ceab-4072-9e75-d25a07f27312' },
		}) // Filling the store
		return {}
	}
</script>

<script lang="ts">	
	import { KitQLInfo } from '@kitql/all-in'

        // works
	KQL_GetResumeById.query({
	 	fetch,
	 	variables: { id: 'fa69f955-ceab-4072-9e75-d25a07f27312' },
	})
</script>

<svelte:head>
	<title>About</title>
</svelte:head>
<KitQLInfo store={KQL_GetResumeById} />
<pre>{JSON.stringify($KQL_GetResumeById.data, null, 2)}</pre>
```

If I change the graphql file to hard-code the id, it works.
```graphql
query GetResumeById {
	resumes_by_pk(id: "myid") {
		id
		name
	}
}
```
```

**Comment by jycouet** [comment]
Yes, `queryLoad` works exactly like `query`. You need to give variables.

And if you have a route like `/routes/resumes/[id].svelte`
you can do:
```svelte
<script context="module" lang="ts">
	import { KQL_GetResumeById } from '$lib/data-access/graphql/_kitql/graphqlStores'
	
        export async function load({ fetch, params }) {
               const id = params.id
		await KQL_GetResumeById.queryLoad({
			fetch, variables: { id }
		}) 
		return {}
	}
</script>
```
And remove the one in the client side if you want to.

Let me know if you got it working

**Comment by gregoryforel** [comment]
My bad, I corrected what I originally wrote. I am indeed providing the variables in `queryLoad`, and it doesn't work. When 

```
 // Does not work
	export async function load({ fetch }) {
		await KQL_GetResumeById.queryLoad({
			fetch,
                        variables: { id: 'fa69f955-ceab-4072-9e75-d25a07f27312' },
		}) // Filling the store
		return {}
	}
```

`KitQLInfo` shows this error message, hence why I think the variables are not passed.
```
...
Variables | null
 
Reset \| cache-firstcache-and-networknetwork-onlycache-only Query
 
Errors:{ "extensions": { "code": "validation-failed", "path": "$" }, "message": "expecting a value for non-nullable variable: \"id\"" }
```

**Comment by gregoryforel** [comment]
I don't have a repo to share but I guess I could put one together.

I'm 100% sure the id exists because the exact same query works when using `load` instead of `queryLoad`.

**Comment by gregoryforel** [comment]
I have no idea what's going on. It's solved now, but even comparing my branches I can't see anything different that solved the issue. Maybe when I deleted Sveltekit's cache or something. I'll close for now, sorry for your time.
