### ISSUE TITLE
Related models are not intelisensed in .gql files

### ISSUE THREAD

**Issue by gevera** [jycouet/kitql#111]
Hi there! First of all, let me tell, KitQL is out of this world.

Unfortuantely I've encounter an issue. I am fetching data from https://github.com/hasura/graphql-engine. Related items could be seen in Hasura, but I get the red underline and no autompletion in VS Code

![image](https://user-images.githubusercontent.com/1085337/162564497-2211fac0-8585-40fd-aa8e-75f7869f654d.png)
![image](https://user-images.githubusercontent.com/1085337/162564575-b75b13dd-ae3b-474a-80f2-9ec9263e1cec.png)

Not the end of the world, but it would be great if KitQL would pick it up. 

Anyways, you just blew my mind by the DX. Thank you for this awesome tool!

**Comment by jycouet** [comment]
Hello, thx for your comment.
Actually, it should be working in VSCode. (on a schéma change sometime you need to reload VSCode.)

On the second screenshot it seems that you have intelisense but not full. 🤔
All this is from the ".graphqlrc" config.

Do you have a public repo to have a look?

**Comment by gevera** [comment]
No, I dont have a repo. But reloading VS Code made the job. So how can I buy you a coffee or a beer? You made my day

**Comment by jycouet** [comment]
No need for a coffee or a beer, just star and spread the word with your kind words 😅

Have fun
