### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by scottBowles** [jycouet/kitql#113]
The documentation contains errors and omissions. As I was getting up and running I had to rely heavily on the demo and made notes of how the docs could be improved to get new users up and running without issue.

I am happy to make a PR with these changes, but I also wouldn't mind a little feedback to ensure that what I have in mind seems right to those of you with a deeper knowledge of KitQL.

### .graphql.yaml
After copying and pasting from the docs, it first complains about tabs. Changing these to spaces fixes that.
Then it says:
```
    Parse configuration [failed]
    → Invalid Codegen Configuration!
```
The simplest fix here is to nest the codegen section under an `extensions:` line.

The demo `.graphql.yaml` has a number of other differences. I'm not sure whether any of these are to be preferred. The above changes get to a minimal working state at least.

### package.json
In the demo app the prepare script was changed to:
`"prepare": "svelte-kit sync && npm run gen"`
I believe this is so that the codegen runs when the prod server installs dependencies. Should this be included in the main docs?

### svelte.config.js
The import
`import watchAndRun from './vite-plugin-watch-and-run.js';` should be changed to
`import watchAndRun from '@kitql/vite-plugin-watch-and-run';`

The run command should be changed from
`run: 'npm run dev'` to
`run: 'npm run gen'`

### kitQLClient.ts
The Getting Started page never mentions this file, but the generated stores file requires it. 

I believe this is a sensible baseline:
```
import { KitQLClient } from '@kitql/client';
	
export const kitQLClient = new KitQLClient({
   url: `https://countries.trevorblades.com/graphql`,
   headersContentType: 'application/json',
   logType: ['client', 'server', 'operationAndvariables'],
});
```

### Other
There is no indication of where to put your graphql operations, or where to import the stores from.

**Comment by jycouet** [comment]
Thx a lot @scottBowles for this issue and the PR. 
That will help others for sure 👍


FYI: 
- operations files can be located where you want. Two places to take care:
  - enabling codegen: `.graphql.yaml`: with `documents: '**/*.gql'`
  - enabling watch mode: `svelte.config.js`: with `watch: '**/*.(gql|graphql)'`
- All stores will be located in `import { KQL_xxx } from '$lib/graphql/_kitql/graphqlStores';`
