### ISSUE TITLE
authentication in ssr (queryLoad)

### ISSUE THREAD

**Issue by david-plugge** [jycouet/kitql#117]
How do i authenticate requests on the server side in sveltekit´s load function?

Using the setHeaders method overrides the global headers so parallel requests may be incorrectly authenticated.

```ts
// src/routes/__layout.svelte
export const load: Load = async ({ session, fetch }) => {

	kitQLClient.setHeaders(
		session.token ? { Authorization: `Bearer ${session.token}` : {}
	);

	await sleep(3000);

	console.log(kitQLClient.getHeaders());

	return {};
};
```

When two clients connect within 3 seconds and only one is logged in, the second requests authentication state is used for the first request aswell.

**Comment by jycouet** [comment]
Thanks for pointing this out.
You would like to set headers per request? as extra settings?

**Comment by david-plugge** [comment]
I´m not sure whats the best idea, per request headers would solve the problem but then you have to add that bit of code in every load function. I usually provide a function via stuff and set the headers in the root layout.

```ts
// src/routes/__layout.svelte
export const load: Load = async ({ session, fetch }) => {
	return {
		stuff: {
			queryLoad: createKitQLQueryLoad({
				fetch, 
				headers: {
					Authorization: `Bearer ${session.token}`
				}
			})
		}
	};
};
```

```ts
// src/routes/index.svelte
export const load: Load = async ({ stuff: { queryLoad }} ) => {
	await queryLoad(KQL_MyQuery);

	return {};
};
```

**Comment by jycouet** [comment]
I don't really like to rely on `stuff`.

I thought that you wanted to have a different `session.token` depending on the query you are doing (`KQL_MyQueryA` or `KQL_MyQueryB`).
But if you have the same `session.token`, it should work already?

Maybe I don't get:
> When two clients connect within 3 seconds and only one is logged in, the second requests authentication state is used for the first request aswell.

I guess that you added `await sleep(3000);` to emphasize the issue, right?

**Comment by david-plugge** [comment]
I dont like it neither, but it does the job in my case.

On the server side, kitQL creates a global Client Instance which is therefore used for every request. If i make changes to the headers to make authenticated request for a specific user, other users may be incorrectly authenticated as that user.

I´ve added the delay to simulate some requests that may take a while to complete.

1. Incoming first request
2. First request sets the clients headers
3. First request is fetching some data
4. Incoming second request
5. Second request sets the clients headers
	-> at this point every new request is using the headers from the second request
6. First request is fetching some other data, but sends the headers from the second request

Hopefully this is easier to understand. Otherwise i can create a repro

**Comment by jycouet** [comment]
Thx for your detailed comment.
I'll have a look at how to solve this in a nice way.

**Comment by orefalo** [comment]
Hi - think I will love this fw - definitely an accelerator.

If I may, I am also quite confused as to how to enable access control. maybe a dedicated page in the document could help.

my 2c

**Comment by nikfp** [comment]
@david-plugge Out of curiosity, can you share your implementation of the `getSession` hook? I assume you have that going so you can populate session info?

**Comment by david-plugge** [comment]
@nikfp i´m using supabase and get the user from a cookie, store that data in locals and polulate it to the session. Nothing special :)

**Comment by jycouet** [comment]
Maybe this can help as well: https://github.com/jycouet/supabase-graphql-example/blob/main/examples/sveltekit

**Comment by david-plugge** [comment]
Thats definately a nice and clean setup.
But it doesnt cover authenticated request in load or am i missing something?
The authorization header is set in the root layout, but that code runs after every load function is called as far as i know.

**Comment by david-plugge** [comment]
The supabase team published auth-helpers for sveltekit

https://github.com/supabase-community/supabase-auth-helpers/blob/next/packages/sveltekit/README.md

**Comment by ymc9** [comment]
Having exactly the same need here. Looking forward to a solution. KitQL is neat!

**Comment by ymc9** [comment]
Maybe instead of importing kitQLClient as a singleton, changing it to a factory could work?

**Comment by nikfp** [comment]
@ymc9 As of now, the way the KQLClient is initialized and then imported into the stores file, it will hard code the values provided into the client when the client is resolved in the stores file. A factory might not behave the way you are expecting, or at least might be a headache as some queries will resolve dependencies on Node and some on the browser. (I might test this though, I'm curious to see what happens) 

_HOWEVER_, in digging through the [source file](https://github.com/jycouet/kitql/blob/main/packages/client/src/lib/toExport/kitQLClient.ts) for the KQLClient another time, it looks like there might be a another way. You gave me an idea on passing info through the request chain instead. 

To start, we would extend the `RequestParameters` object type to accept a headers object.  

```ts
export declare type RequestParameters<V> = {
  fetch?: typeof fetch;
  variables?: V;
  headers?: {[key: string]: string};  
};
```
This type gets exported and picked up in the generated stores, so type safety would flow through as expected. Then each store query calls the `request` method of the KQLClient, so we just extend the input args with a headers type: 

```ts
public async request<D, V>({
  skFetch,
  document,
  variables,
  operationName,
  operationType,
  browser,
  perRequestHeaders // note new input, should be optional
}): Promise<ResponseResult<D, V>> {
  
  // setup code before request

  try {

    // Build headers object to send with request
    // Per-Request headers will overwrite existing headers during merge
    const sendHeaders = perRequestHeaders ? {...this.headers, ...perRequestHeaders} : {...this.headers}

    const res = await fetchToUse(this.url, {
      method: 'POST',
      credentials: this.credentials,
      // use the built headers
      headers: { ...sendHeaders, 'Content-Type': this.headersContentType },
      body: JSON.stringify({
        query: print(document),
        variables
      })
    });

    // remainder of request logic
    
  } catch (errors) {
    dataToReturn.errors = [errors];
    return dataToReturn;
  }
}
```

This could satisfy the needs of the OP and still keep the default values set in the class creation for future use. 

This would mean some tinkering with the way the stores are generated and with the KQLClient code, but it appears that it would work. Before I do anything like a PR though I'd like to hear from @jycouet as he might have already solved this, so my idea might be moot.

**Comment by jycouet** [comment]
Thx a lot for all your comments.
Nice to see people involved 👍

I would suggest to not start a PR about this right now as a lot of things

**Comment by jycouet** [comment]
Sorry, I leave it open for now to keep track of it 😁
(working from my phone right now)

**Comment by orefalo** [comment]
Is it related to this?
https://github.com/HoudiniGraphql/houdini/pull/291

**Comment by jycouet** [comment]
Yes @orefalo 👍
Add we have to explain a bit the work flow we have in mind 😉

**Comment by orefalo** [comment]
Bien!

Now I connect the dots.

I was researching another good lib for svelte+gql and found houdini. Was surprise to see a pull req with your name on it.

Looking forward to it.
Sincerely,

**Comment by nikfp** [comment]
I'm excited to see how this plays out. I was about to start working on a testing workflow for KitQL and _try_ to get the loading states integrated with Storybook as mocks, but now that I know things are changing for the better I'll hold off. Looks like the Houdini PR has almost 100 commits since last Friday between just 2 authors, you fols have been busy!

**Comment by jycouet** [comment]
It took time, but it finally happened 🥳

Check out the [Announcement here](https://github.com/jycouet/kitql/discussions/156#discussioncomment-3080343)

---

Basically, you can do what you want, before and after the fetch (server-side or client-side)

Here is an example 👇
```ts
import type { RequestHandlerArgs } from '$houdini';
import { HoudiniClient } from '$houdini';
import { stry } from '@kitql/helper';

// For Query & Mutation
async function fetchQuery({
  fetch,
  text = '',
  variables = {},
  session,
  metadata
}: RequestHandlerArgs) {
  // Prepare the request
  const url = import.meta.env.VITE_GRAPHQL_ENDPOINT || 'http://localhost:4000/graphql';

  // regular fetch (Server & Client)
  const result = await fetch(url, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      Authorization: `Bearer ${session?.token}` // session usage example
    },
    body: JSON.stringify({
      query: text,
      variables
    })
  });

  // return the result as a JSON object to Houdini
  const json = await result.json();

  // metadata usage example
  if (metadata?.logResult === true) {
    console.info(stry(json, 0));
  }

  return json;
}

// Export the Houdini client
export const houdiniClient = new HoudiniClient(fetchQuery);

```

Enjoy 🎉
