### ISSUE TITLE
CORS Issue

### ISSUE THREAD

**Issue by Auxtal** [jycouet/kitql#124]
`Access to fetch at 'http://localhost:5000/graphql' from origin 'http://localhost:3000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: Redirect is not allowed for a preflight request.`

This error only occurs in the console when I redirect to a page that has a request take for example my premium page:
```html
<script context="module" lang="ts">
  export async function load({ fetch, session }) {
    let user = session?.user
    if (!user) {
      return {
        redirect: "/discord/login",
        status: 302,
      }
    }

    await KQL_GetUserGuilds.queryLoad({
      fetch,
      variables: { user_id: user.id },
    })

    return { props: { user } }
  }
</script>

<script>
  import Nav from "$lib/components/Nav.svelte"
  import { onMount } from "svelte"
  import { loadStripe } from "@stripe/stripe-js"
  import * as env from "$lib/utils/env"
  import { getApi } from "$lib/utils/requests"
  import { KQL_GetUserGuilds } from "$lib/graphql/_kitql/graphqlStores"

  const STRIPE_PUBLISHABLE_KEY = env.STRIPE_PUBLISHABLE_KEY
  let stripe = null
  let loading = false
  let guild_selected

  onMount(async () => {
    stripe = await loadStripe(STRIPE_PUBLISHABLE_KEY)
  })

  async function startCheckout() {
    loading = true

    let checkout = await getApi(
      `stripe/${guild_selected}/${user.id}/${user.email}/create-session`
    )

    let { error } = await stripe.redirectToCheckout({
      sessionId: checkout.session_id,
    })

    if (error) {
      console.error(error)
    }
  }

  $: guilds = $KQL_GetUserGuilds.data?.GetUserGuilds?.guilds
  export let user
</script>
```

my graphql endpoint has CORS setup so I'm not to sure why this is ocurring:
```py
@_graphql.route("/", methods=["GET"])
@ipc_available
async def graphql_playground():
    return ariadne.constants.PLAYGROUND_HTML


@_graphql.route("/", methods=["POST"])
@route_cors(allow_methods=["POST"])
@authenticated
@ipc_available
async def graphql_server():
    data = await request.get_json()
    success, result = await ariadne.graphql(
        schema, data, context_value=request, debug=current_app.debug
    )
    status_code = 200 if success else 400

    return jsonify(result), status_code

```

**Comment by jycouet** [comment]
Hi, 
I just added in the doc the credentials section: https://kitql.vercel.app/docs/usages/tips#credential
Could you try various values? and Let me know.

**Comment by Auxtal** [comment]
Tried all three options in my `kitQLClient` and restarted each time, going back and fourth same error raises in the console.

**Comment by jycouet** [comment]
What's the language of the server? (sorry, I don't know) 
On the server, if you comment Cors, is it working? (I belive not as without cors settings I would restrict even more!) 
Can't you whitelist on your server the client 'localhost:3000'?

I'm pretty sure, any graphql client have the same issue, no?

**Comment by jycouet** [comment]
Any news on this? 
I think that it's a server-side issue. 

Feel free to re-open if you have more info.
