### ISSUE TITLE
@kitql/all-in does not work with pnpm 

### ISSUE THREAD

**Issue by nhe23** [jycouet/kitql#136]
### Describe the problem
When I follow the [Get started](https://www.kitql.dev/docs/all-in) guide with pnpm I'm facing several issues. 
- @kitql/vite-plugin-watch-and-run.js is not found -> I solved this by adding it manually to my package.json and changing the import to `import watchAndRun from '@kitql/vite-plugin-watch-and-run';`
![image](https://user-images.githubusercontent.com/19340684/168990129-46609aa1-8241-4e3c-82a8-314426b55b9b.png)

- graphql-codegen not found. It seems like installing kitql/allin with pnpm does not really install the dependencies of kitql.
![image](https://user-images.githubusercontent.com/19340684/168990368-b7848b37-5a17-454d-a8c6-8a8ed3838b19.png)

### Reproduction repo
I created a minimal reproduction repo here: https://github.com/nhe23/kitql-pnpm-bug

#### System:
    OS: macOS 12.3.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 93.14 MB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  #### Binaries:
    Node: 17.9.0 - ~/.volta/tools/image/node/17.9.0/bin/node
    Yarn: 1.22.18 - ~/.volta/tools/image/yarn/1.22.18/bin/yarn
    npm: 8.5.5 - ~/.volta/tools/image/node/17.9.0/bin/npm
  #### Browsers:
    Brave Browser: 101.1.38.111
    Chrome: 101.0.4951.64
    Firefox: 100.0
    Safari: 15.4

**Comment by motopods** [comment]
try pnpm 6.x, not 7.0

**Comment by nhe23** [comment]
> try pnpm 6.x, not 7.0

Tried both versions ... does not make a difference.

**Comment by nhe23** [comment]
Thank you for taking a look and resolving this issue so quickly. 

> I'm not a day to day user of pnpm, so I don't know why it's like this by default.

Actually pnpm installs the graphql-codegen package (in its global directory) but does not add a symlink in the projects node_modules as it does this only for the packages that are in the package.json. This way your node_modules are not polluted by the dependencies of your dependencies of your dependencies (and so on 😄) which I like as a default behaviour. Thats why the pattern of @kitql/all-in does not work by default with pnpm. For me the best solution was to just add the dependencies directly to my package json.

> Maybe I should gain more knowledge about this package manager as it seems promising

I can only recommend it as it saves me so much time working with many projects that have similar dependencies. It also works great for monorepos and changeset management (End of ad 😄 )

> 4/ I'm curious, why starting to replicate de demo1 and not cloning it / Stackblitz it?

Would have been easier but I wanted to have a repo that exactly followed the getting started guide.

**Comment by hare0319** [comment]
> Hey there, I had a look and here are my few points 🧑‍💻
> 
> ## 1/ @kitql/vite-plugin-watch-and-run.js is not found
> It was a typo in the doc of KitQL that is now fixed: https://www.kitql.dev/docs/all-in you have to import like this: `import watchAndRun from '@kitql/vite-plugin-watch-and-run'`
> 
> ## 2/ graphql-codegen not found
> By default `pnpm` doesn't install deps your deps. (so it's not installing deps of `@kitql/all-in`) To go around this, you can add a file `.npmrc` with `node-linker=hoisted` And then, when you do `pnpm i`, you will get deps of deps. => PERFECT 🥳 _I'm not a day to day user of `pnpm`, so I don't know why it's like this by default... Maybe I should gain more knowledge about this package manager as it seems promising, but today I don't see it! Apparently you can also manage this by pattern... scripting... https://pnpm.io/pnpmfile. I let you discover_
> 
> ## 3/ reproduction ✅
> Thx a lot for the reproduction, it's easy to guide people when you spent the time to provide this. I did a PR to it to show all steps to fix the beginning: [nhe23/kitql-pnpm-bug#1](https://github.com/nhe23/kitql-pnpm-bug/pull/1) 🥳
> 
> ## 4/ I'm curious, why starting to replicate de demo1 and not cloning it / Stackblitz it?
> Yes, in https://www.kitql.dev/docs/demos/01_demo-01, I show two ways to get the code:
> 
> * Clone locally (`degit`)
> * Using `Stackblitz` button to be able to use it directly in the browser... Where you can try and find out things
> 
> I think that the issue is solved, if you have any thing else, do not hesitate to re open 👍

I got the same issues here. Thanks very much for the solution.

I also prefer to replicate the demo, as I may need to combine this with my other proj/packages.

Thanks very much.
