### ISSUE TITLE
🐛 watchKind option on @kitql/vite-plugin-watch-and-run not working

### ISSUE THREAD

**Issue by jbruxelle** [jycouet/kitql#14]
To reproduce : 

* Create a watch and run entry with watchKind 'ADD' ;
* Save a file with the specified extension ;
* The command runs ;

**Comment by jycouet** [comment]
Did you restart the server? And check again?

If it's still not working well, will you do a PR?

**Comment by JulianBruxelle** [comment]
I restarted yes, but I can't figure out where it comes right now. 
I'll try to investigate later.

**Comment by jycouet** [comment]
So, you don't see the issue anymore? 

When I do a change of config, I always need to restart the process on my side to have it working.
(And I don't know why)

**Comment by JulianBruxelle** [comment]
Maybe having the vite-plugin-watch-and-run in a Sveltekit project (as done recently for @kitql/client) could help debug this ?

**Comment by jycouet** [comment]
I can't reproduce, for me it's working well.
We have a look tomorrow morning? 💪

**Comment by jycouet** [comment]
I close the issue as I can't reproduce.
Please open it again if it's not working on your side.
