### ISSUE TITLE
Using prefetch to a page with the same store but different variables causes the page to change immediately

### ISSUE THREAD

**Issue by scottBowles** [jycouet/kitql#150]
I'm not sure whether this is something to be fixed or worked around, or if there's already a way to handle it that I can't find. I'm at least curious how others have handled this issue.

When you put `sveltekit:prefetch` on an anchor that goes to a page using the same store but different variables, the page's content updates as soon as the prefetched page's data loads.

For instance, imagine you have a `KQL_PlaceById` store which loads for a given place's detail page. If one detail page links to another with `sveltekit:prefetch` on the anchor, when a user hovers over the link the `KQL_PlaceById` store loads with that prefetched place's data. Since the current page is relying on that store for display, it updates immediately, whether the user clicks the prefetched link or not.

I'm thinking I'll get around this by creating a store that holds an object mapping query variables to PlaceById query results with those variables. I wonder whether it would be good to have a similar solution built in, or if there's some way to handle this that I am missing. Thanks!

**Comment by jycouet** [comment]
Hi @scottBowles, 
Yes, today, it's a limitation of KitQL store. You can have only 1 set of variables displayed at the same time.

I usually say that one way is to create a second store (second query). Something like MainQuery / DetailQuery.
But in your example, it will not do the trick as far as I understand.
Another way is to not `sveltekit:prefetch` . While I like a lot this feature, you have to be careful to use it... in some cases, it's maybe not sooo good. When you have 20 links and the user hover all on them to finally just go to the last one. Or you put the query not in the load to have it only "client side" mode. Like this you can do `sveltekit:prefetch` & have only 1 storeVariable at the time.

I'm already curious about your answer 🥸

**Comment by jycouet** [comment]
This took a bit of time in Houdini to get it right _(poke @AlecAivazis ^^)_
But, `prefetch` is now woking well with stores 🎉

Check out the [Announcements here](https://github.com/jycouet/kitql/discussions/156#discussioncomment-3080343)
