### ISSUE TITLE
.kitql.yaml config doesn't work properly

### ISSUE THREAD

**Issue by hare0319** [jycouet/kitql#159]
Hey,

Thanks very much for this fantastic repo.

I just grab the demo2 proj to play with. And found that the
`module-codegen` try to read `.kitql.yaml` config for generating
modules. However, it seems that the config doesn't quite match
the parser, i.e. `module-codegen/index.js`. This will fail the whole
generation process.

Best,

Sc

**Comment by jycouet** [comment]
I'll have a look. Thx for the notice.

**Comment by jycouet** [comment]
On my side, it's working well. 
Could you give me a bit more info?
