### ISSUE TITLE
✏️ TYPO: vite-plugin-watch-and-run isRunnig shoud be isRunning

### ISSUE THREAD

**Issue by JulianBruxelle** [jycouet/kitql#16]
https://github.com/jycouet/kitql/blob/55a84005895c67b63aaf8be70669e4d464d47e8f/packages/vite-plugin-watch-and-run/src/index.ts#L31

**Comment by jycouet** [comment]
I'm saving some bytes 🤣

**Comment by jycouet** [comment]
https://github.com/jycouet/kitql/commit/4aad9e39a091e0bf34ab49e545c9ba605960f491
