### ISSUE TITLE
global fetcher

### ISSUE THREAD

**Issue by grind-t** [jycouet/kitql#161]
Hello! 
I played around with the library a bit and I really liked it. It would be nice if a global fetcher could be passed to the client. For example, we need it to read the trace from the response header 😅

**Comment by jycouet** [comment]
Good news, it's coming soon.
Follow https://github.com/jycouet/kitql/discussions/156 to know what is going on and track the progress.

I leave this issue open until the new version out.

**Comment by jycouet** [comment]
It took time, but it finally happened 🥳

Check out the [Announcement here](https://github.com/jycouet/kitql/discussions/156#discussioncomment-3080343)

---

Basically, you can do what you want, before and after the fetch (server-side or client-side)

Here is an example 👇
```ts
import type { RequestHandlerArgs } from '$houdini';
import { HoudiniClient } from '$houdini';
import { stry } from '@kitql/helper';

// For Query & Mutation
async function fetchQuery({
  fetch,
  text = '',
  variables = {},
  session,
  metadata
}: RequestHandlerArgs) {
  // Prepare the request
  const url = import.meta.env.VITE_GRAPHQL_ENDPOINT || 'http://localhost:4000/graphql';

  // regular fetch (Server & Client)
  const result = await fetch(url, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      Authorization: `Bearer ${session?.token}` // session usage example
    },
    body: JSON.stringify({
      query: text,
      variables
    })
  });

  // return the result as a JSON object to Houdini
  const json = await result.json();

  // metadata usage example
  if (metadata?.logResult === true) {
    console.info(stry(json, 0));
  }

  return json;
}

// Export the Houdini client
export const houdiniClient = new HoudiniClient(fetchQuery);

```

Enjoy 🎉
