### ISSUE TITLE
Check for existing folders in modules for better error analysis

### ISSUE THREAD

**Issue by Nukiloco** [jycouet/kitql#177]
**Is your feature request related to a problem? Please describe.**
Currently from just a bunch of testing, if your missing a folder like "typedefs" it will generate a blank typedefs.ts file which will make GraphQL produce a EOF error.

**Describe the solution you'd like**
A solution is to give feedback when a folder is missing from modules.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by jycouet** [comment]
I'll have a look RN

**Comment by jycouet** [comment]
Should be fixed next version
