### ISSUE TITLE
Graphiql

### ISSUE THREAD

**Issue by david-plugge** [jycouet/kitql#196]
**Is your feature request related to a problem? Please describe.**

It would be nice to have a simple way to add graphiql to an existing sveltekit project.

**Describe the solution you'd like**

Create a package `@kitql/graphqli` that exports a sveltekit handle function doing the work.

**Describe alternatives you've considered**

I can create the package in my own but i thought it would be a nice fit for the kitql stack

**Additional context**

This is what i currently use.

```ts
// src/lib/graphiql.ts
import type { GraphiQLOptions as Options } from '@graphql-yoga/common';
import { renderGraphiQL } from '@graphql-yoga/render-graphiql';
import type { Handle } from '@sveltejs/kit';

type GraphiQLOptions = Omit<Options, 'headers'> & {
	headers?: Record<string, string>;
	path?: string;
};

export default function graphiql(options: GraphiQLOptions): Handle {
	const { path, headers, ...opts } = {
		path: '/graphiql',
		...options
	};

	const body = renderGraphiQL({
		...opts,
		headers: JSON.stringify(headers ?? {})
	});

	return ({ event, resolve }) => {
		if (event.url.pathname !== path) return resolve(event);

		return new Response(body, {
			status: 200,
			headers: {
				'Content-Type': 'text/html'
			}
		});
	};
}


// src/hooks.ts
import { sequence } from '@sveltejs/kit/hooks';
import graphiql from '$lib/graphiql';
export const handle = sequence(graphiql({
	endpoint: import.meta.env.GRAPHQL_ENDPOINT,
	headers: {
		...
	}
}));
```

**Comment by jycouet** [comment]
Here is what I'm using: https://github.com/jycouet/kitql/blob/main/examples/demo2/src/routes/api/playql.ts

Isn't it sufficient? 🤔

**Comment by david-plugge** [comment]
I just thought about putting everything in a seperate package.
But yeah its not that much code maybe this is not needed.

**Comment by jycouet** [comment]
I like a lot the idea, but in the end I think in amount of code if will be about replacing
`import { renderGraphiQL } from '@graphql-yoga/common';` by `import { renderGraphiQL } from '@kitql/graphiql';` or something like this.

In your example, you must also add a route `/routes/graphiql.ts`. Right?

**Comment by jycouet** [comment]
I start to like it even more!

And with `sequence` it's also very nice!
Why not do the same for the endpoint? (instead of having a `/api/graphql.ts` file?)

**Comment by david-plugge** [comment]
Thats possible for sure.
I didnt´t use the server side of kitql yet so im not familiar with that. 
The graphql endpoint isn´t that complicated and all imported files are within the project. [server.ts](https://github.com/jycouet/kitql/blob/main/examples/demo2/src/lib/graphql/server.ts) could export a handle function but other than that i´m not sure if there is any benefit.

If this is a thing all handle functions can be combined like in [Supabase Auth helpers](https://github.com/supabase-community/auth-helpers/blob/main/packages/sveltekit/src/handlers/auth.ts).

**Comment by jycouet** [comment]
I'm sure there is something to do similar to Supabase Auth helper!
And even make KitQL auto _authable_ with supabase 👍

Where could we what about it? 🎉

**Comment by jycouet** [comment]
Hi @david-plugge , it's almost done, and I love it! You can have a look here: https://github.com/jycouet/kitql/pull/215

Looking at `@supabase/auth-helpers-sveltekit`, I have 2 questions for you: 
- By default, you would go for path: `/graphiql` or `/api/graphiql` (closer to supabase?)
- You would name the handle: `graphiql` or `handleGraphiql` (closer to supabase?)

**Comment by david-plugge** [comment]
Wow awesome work!

- I think i prefer `/graphiql` since it´s not really an api i guess?
- `handleGraphiql` is more descriptive about whats going on and where to put that function

**Comment by jycouet** [comment]
All right, I'll start with:

✅ handleGraphiql 
✅ /graphiql

✅ handleGraphql 
✅ /graphql

**Comment by jycouet** [comment]
Do you care about having `graphiql` locally (in your dep)? Or it's OK downloading in runtime?

**Comment by david-plugge** [comment]
> downloading in runtime

What exactly do you mean?

**Comment by jycouet** [comment]
Two options: 
1/ "Online" (you need internet)
2/ "Offline" (you don't need internet) https://www.the-guild.dev/graphql/yoga-server/docs/features/graphiql#offline-usage

**Comment by david-plugge** [comment]
Okay i read through the docs and i think online by default is the way to go. But maybe using an async import to check if the user installed the package himself?

**Comment by jycouet** [comment]
I'll start with this default. 
And we can add later the `offline: true` mode doing this async import ?

**Comment by david-plugge** [comment]
Sounds good :) i dont think you even need to have it as a config option

```ts
try {
	const { renderGraphiQL } = await import('@graphql-yoga/render-graphiql');
} catch (err) {
	// user did not add it as a dependency
}
```

One question, is graphqli also added in production? It would be nice to omit it there

**Comment by jycouet** [comment]
Hooo nice! And pretty easy ;)
Only annoying thing is that I need to add an `await` in the sequence

```ts
import { dev } from '$app/environment'

export const handle = sequence(
  // Rignt now I have:
  handleGraphql(kitqlServer),
  await handleGraphiql({
    enabled: dev,
  })

  // But maybe an option is to have
  handleGraphql(kitqlServer),
  handleGraphiql({
    enabled: dev,
  })
  await handleGraphiqlOffline({
    enabled: dev,
  })
)
```

--- 

Also, there is already a enabled flag 👍

**Comment by david-plugge** [comment]
You can get rid of the await like this:

```ts
async function getGraphiQLBody(graphiqlOptions) {
  try {
    const { renderGraphiQL: renderGraphiQLOffline } = await import('@graphql-yoga/render-graphiql')
    return renderGraphiQLOffline(graphiqlOptions)
  } catch (err) {
    // user did not add it as a dependency
    const { renderGraphiQL: renderGraphiQLOnline } = await import('@graphql-yoga/common')
    return renderGraphiQLOnline(graphiqlOptions)
  }
}

export function handleGraphiql(options?: GraphiQLOptions): Promise<Handle> {
  const { graphiQLPath, headers, enabled, ...opts } = {
    title: 'KitQL',
    endpoint: '/graphql',
    graphiQLPath: '/graphiql',
    enabled: true,
    ...options,
  }

  if (!graphiQLPath.startsWith('/')) {
    throw new Error("graphiql graphiQLPath must start with '/'")
  }

  const graphiqlOptions = {
    ...opts,
    headers: JSON.stringify(headers ?? {}),
  }

  const bodyPromise = getGraphiQLBody(graphiqlOptions)

  return async ({ event, resolve }) => {
    if (enabled && event.url.pathname === graphiQLPath) {
      return new Response(await bodyPromise, {
        status: 200,
        headers: {
          'Content-Type': 'text/html',
        },
      })
    }

    // Fallback to normal request
    return resolve(event)
  }
}
```

**Comment by david-plugge** [comment]
I sadly don´t have that much time atm to play around with kitql but i think this issue can be closed now?

**Comment by jycouet** [comment]
It's done, I just need to publish the version. (I'll try to do it today and close the issue 👍)
