### ISSUE TITLE
useTypeImports: true is not respected => produces standard imports in moduleTypes

### ISSUE THREAD

**Issue by frankmayer** [jycouet/kitql#234]
### Describe the bug

First of all thank you for your efforts and this promising tool. :+1: 

As the title states, there seems to be an issue when creating moduleTypes

When I run `pnpm check:watch` I get this error for both import lines in that file:
```
Error: This import is never used as a value and must use 'import type' because 'importsNotUsedAsValues' is set to 'error'. 
```

### Your Example Website or App

https://stackblitz.com/fork/github/jycouet/kitql/tree/main/examples/demo-init?title=KitQL%20Demo%202

### Steps to Reproduce the Bug or Issue

2 ways
A)  Check your KitQL Demo on Stackblitz. 
1. Go to the moduleTypes.ts file and check the imports

B) on any project
1. Generate types by doing `pnpm gen:types`.
2. Check the following imports in `moduleTypes.ts`
They are showing:
```
import * as Types from "$graphql/$kitql/graphqlTypes";
import * as gm from "graphql-modules";
```

### Expected behavior

They should be showing (note the `type` addition):
```
import type * as Types from "$graphql/$kitql/graphqlTypes";
import type * as gm from "graphql-modules";
```

### Platform

latest kitql (https://github.com/jycouet/kitql/commit/8a6cd20116453d945653545ea58b0b6034f09500)

### Additional context

I have not looked in too deep, but it looks a lot like this issue https://github.com/dotansimha/graphql-code-generator/issues/5478 in another part of https://github.com/dotansimha/graphql-code-generator, but this time it is in codegen-cli, which you are using under the hood, if I am not mistaken.

**Comment by jycouet** [comment]
Thank you for reporting this.

Yes you are right, `useTypeImports` is not handle in `preset: graphql-modules` of `graphql-code-generator`. I will fix the upstream and include it here in the coming days.

**Comment by jycouet** [comment]
With `"@kitql/all-in": "0.8.0-next.11"` is should be fixed. 
Could you confirm and close the ticket?

**Comment by frankmayer** [comment]
Hi @jycouet, I can confirm this is fixed. Thank you! :+1:
