### ISSUE TITLE
Documentation / examples / demos no longer reflect the code and don't work

### ISSUE THREAD

**Issue by bgronek** [jycouet/kitql#255]
### Describe the bug

I've been trying to get kitql and, specifically, houdini, to work for two days now. Great idea, but I'm sensing that there is a lot of change which is invalidating the documentation, published blog posts and, well, anything providing a coherent example of how to get this to work. 

The Houdini Getting Started actually fails at 'npm i' due to outdated dependencies that cannot reconcile. 
https://www.houdinigraphql.com/intro/welcome

I say this not because I'm trying to insult your effort. It looks like a very impressive project which I'd love to get working, but instead to call out something that needs to be addressed in order to keep this project from dying on the vine.

Best of luck!

### Your Example Website or App

Your example at https://www.houdinigraphql.com/intro/welcome

### Steps to Reproduce the Bug or Issue

1. Go to https://www.houdinigraphql.com/intro/welcome
2. Try running the example.
3. npm i results in many errors.

### Expected behavior

A working example of the houdini project.

### Platform

- OS: macOS
- NodeJS: 18.10.0
- The example at https://www.houdinigraphql.com/intro/welcome 

### Additional context

I'm posting here as Kitql has incorporated houdini.

**Comment by jycouet** [comment]
Hi, and thank you for reaching out, it's always good to know where we stand. 
And I'm sorry for your current experience that doesn't look great for now. Let's change this 👌. 

First, a question : will you host your graphql endpoint in sveltekit? 

Then, few points:
- I have to release kitql to align doc and the package. Today, you are right, it's not synchronized. 
- I'll check houdini's getting started as it should work. (maybe a node issue? A package manager one? Or an update!) 
- did you try an empty project initializing houdini? `npx houdini init`? 
- did you try https://www.kitql.dev/docs/demos/01_demo-init
- blog post was written a few months ago and yes it's outdated. I think that we should not update it, but create new ones. Once we will fix your situation, it would be a great contribution from the community 🎉
- I did a talk about houdini Monday, the YouTube video should be published in coming days on Svelte society 🤞

I'll dig in the few points for me and let you know. 
Feel free to react out on the svelte Discord.

**Comment by JacobArrow** [comment]
I am in the exact same boat as you @bgronek! 
I've used an evening trying to get KitQL to work, but without any success.
The documentation does not match with recent changes and I have not been able to find a tutorial with correct information.
A more up-to-date getting started tutorial would be much appreciated

**Comment by jycouet** [comment]
I'm sorry to read that.
Did you try the `demo-init`?

As Yoga v3 was released, I will release KitQL asap.

🤞

**Comment by bjornet** [comment]
I have the same issue. I can confirm that the `demo-init` does not build on Stack Blitz and when I try it out locally `npx degit jycouet/kitql/examples/demo-init demo-init` the TS server points to the fact that some imports are unreachable and some types are wrongly implemented – some quick examples of this;

`import { resolvers } from './$kitql/resolvers';` in  `demo-init/src/lib/modules/user/index.ts`
`KitQLHandleGraphQL<IKitQLContext>` in `demo-init/src/lib/graphql/kitqlServer.ts`

Thank you for the great work so far ⭐. I hope for the documentation/demo to be fixed so that I can get fully introduced to KitQL soon, it looks really promising 👍🏽 🌮

**Comment by jycouet** [comment]
@bjornet @JacobArrow @bgronek could you check now?
I updated the version & the doc.

**Comment by jycouet** [comment]
It should be working now.
Please re open if you have an issue
