### ISSUE TITLE
Stackblitz demo init not working

### ISSUE THREAD

**Issue by KillianGDK-FDTI** [jycouet/kitql#269]
### Describe the bug

Seems like there is an update on that breaks the demo app, and the overall package as well.
Maybe linked to https://github.com/dotansimha/graphql-code-generator/issues/8200 ?

### Your Example Website or App

https://stackblitz.com/edit/jycouet-kitql-p7cpk8?file=README.md&title=KitQL%20Demo%202

### Steps to Reproduce the Bug or Issue

Go to the demo init app

### Expected behavior

I expect it to be working, I tried on local as well.

### Screenshots or Videos

```js
failed to load config from /home/projects/jycouet-kitql-fskbe2/vite.config.ts
error when starting dev server:
file:///home/projects/jycouet-kitql-fskbe2/node_modules/@graphql-codegen/cli/esm/codegen.js:1
import { DetailedError, normalizeOutputParam, normalizeInstanceOrArray, normalizeConfig, getCachedDocumentNodeFromSchema, isDetailedError, } from '@graphql-codegen/plugin-helpers';
         ^^^^^^^^^^^^^
SyntaxError: The requested module '@graphql-codegen/plugin-helpers' does not provide an export named 'DetailedError'
    at async loadConfigFromBundledFile (file:///home/projects/jycouet-kitql-fskbe2/node_modules/vite/dist/node/chunks/dep-0ebb5606.js:63560:21)
    at async loadConfigFromFile (file:///home/projects/jycouet-kitql-fskbe2/node_modules/vite/dist/node/chunks/dep-0ebb5606.js:63455:28)
    at async resolveConfig (file:///home/projects/jycouet-kitql-fskbe2/node_modules/vite/dist/node/chunks/dep-0ebb5606.js:63072:28)
    at async createServer (file:///home/projects/jycouet-kitql-fskbe2/node_modules/vite/dist/node/chunks/dep-0ebb5606.js:62138:20)
 ELIFECYCLE  Command failed with exit code 1.
```

### Platform

- OS: [e.g. macOS, Windows, Linux]
- NodeJS: [e.g. 18.1.0]
- `@kitql/*` version(s): [e.g. 2.5.1]

**Comment by jycouet** [comment]
I'll fix it this week.
Thx for reporting 👍

**Comment by BSBjorn** [comment]
Did you find a solution for this? I'm having the same issue...

` ERROR  The requested module '@graphql-codegen/plugin-helpers' does not provide an export named 'DetailedError'              

  import { DetailedError, createNoopProfiler } from '@graphql-codegen/plugin-helpers';`

**Comment by jycouet** [comment]
Let me fix it now, give me a few minutes 👍

**Comment by jycouet** [comment]
It should be fixed.
Try it again _(make sure it's using `"@kitql/all-in": "0.8.0-next.21"`)_

Maybe you can try it locally with:
```bash
npx degit jycouet/kitql/examples/demo-init demo-init
```

I close the issue, if you have any issue please comment / re open / open a new ticket. 👍
