### ISSUE TITLE
[PACKAGES] vite-plugin-watch-and-run - Ability to specify which shell to use to execute command

### ISSUE THREAD

**Issue by MattPurland** [jycouet/kitql#348]
Currently the vite-plugin-watch-and-run package has the spawn 'shell' parameter hard-coded to true:

https://github.com/jycouet/kitql/blob/1de29c9722940a54fb6646d57e91d61b3512f046/packages/vite-plugin-watch-and-run/src/index.ts#LL189C21-L189C26

which in the case of Windows uses cmd to execute the command. Could the plugin be updated allowing the user to specify which shell to use with true being the default? For example:

```
watchAndRun([
    {
        name: 'ssr',
        watchKind: ['add'],
        watch: resolve(projectRootDir, 'bootstrap/ssr/ssr.js'),
        run: 'pm2 restart ssr -s',
        delay: 300,
        shell: 'powershell.exe'
    }
])
```

I'm currently having to use 'powershell.exe "pm2 restart ssr -s"' as my run command, which works, but I get 2 cmd windows flash up, which isn't an ideal development experience.

Another point of view is that I'm running vite via powershell, so could the plugin detect that and in turn execute commands via powershell instead of the above?

**Comment by jycouet** [comment]
Could you check on your  end?  Thx

**Comment by jycouet** [comment]
Reopen if you face anything 👍
