### ISSUE TITLE
🚀 Caching improvements

### ISSUE THREAD

**Issue by jycouet** [jycouet/kitql#38]
- [x] InMemory
- [x] LocalStorage (from `@kitql/all-in@0.2.5`) thx @lukaszwisniewski88 
- [ ] IndexedDB

**Comment by frederikhors** [comment]
Yes, but also localStorage for now. I would create adapters. Let's start with the simplest thing.

**Comment by frederikhors** [comment]
https://github.com/macfja/svelte-persistent-store for use or inspiration?

**Comment by jycouet** [comment]
I saw it and it looks good. But do we need all options?
I'm not sure where to put it:
- in generator with a config flag?
- in a config at KitQL lib level?
- at each store level?

**Comment by jycouet** [comment]
#59

**Comment by lukaszwisniewski88** [comment]
I think we can use a string type of cache type in client options. 

for example 
```ts
export const kitQLClient = new KitQLClient({
	url: `https://countries.trevorblades.com/graphql`,
	headersContentType: 'application/json',
	logType: ['client', 'server', 'operationAndvariables'],
	
       // choose which type of cache to use : 'localStorage' or 'inMemory' .. etc or pass an instance of ICacheData 
       cacheImplementation: 'inMemory',
});

```
Maybe it could be easier for a lib users.

**Comment by jycouet** [comment]
Fully agree.
Like this, all implementations will all be in KitQL directly 👍

**Comment by jycouet** [comment]
At the same time, it should probably be `clientCacheImplementation`

**Comment by jycouet** [comment]
I wonder if it should be possible to overwrite it at the query level? (like cache value?)
Or at configuration level per operation? (of course, all typed!)

```ts
export const kitQLClient = new KitQLClient({
	url: `https://countries.trevorblades.com/graphql`,
	headersContentType: 'application/json',
	logType: ['client', 'server', 'operationAndvariables'],
	defaultClientCacheTime: 3*60*1000
        defaultClientCacheImplementation: 'inMemory',
       
       overwrite: {
          KQL_AllContinents: { 
            clientCacheTime: 60*60*1000 // 1 hour
            clientCacheImplementation: 'localStorage',
          }
       }
});
```

**Comment by lukaszwisniewski88** [comment]
It could be possible. I think the best aproach would be to overwrite it at the query level.

Globally will use one type of cache, and for some stores using another. I think it would be leaner.

**Comment by jycouet** [comment]
We have 3 options: 

1/ Globaly
```ts
export const kitQLClient = new KitQLClient({
  ...
  defaultClientCacheImplementation: 'inMemory',
  ...
});
```

2/ Query config overwrite
```ts
export const kitQLClient = new KitQLClient({
  ...
  overwrite: {
    KQL_AllContinents: { 
      clientCacheImplementation: 'localStorage'
    }
  }
  ...
});
```

3/ Query usage
```ts
await KQL_AllContinents.query({
  variables: { ... },
  settings: { clientCacheImplementation: 'localStorage' }
});
```

Option 1 and 2 make sense. Option 3, I'm not sure as we could mix things fast.

**Comment by lukaszwisniewski88** [comment]
Option 2 looks nice, and it would be possible if every store creates it's own instance of a kitQl Client, 

:boom: breaking change, instead of creating a client for all, user should export a factory function which will be used by a store to create an instance of the client. 

```ts
export const createKitQLClient = ()=>new KitQLClient({...options }}});
```

**Comment by jycouet** [comment]
I'll archive this "Caching improvements" issue as we will not have `indexedDb` in this form of `KitQL`.
In a few days, we will open a new discussion with another angle. 🤞
