### ISSUE TITLE
vite-plugin-watch-and-run 1.4 has no CJS modules

### ISSUE THREAD

**Issue by kobleistvan** [jycouet/kitql#401]
### Describe the bug

Hi! Version 1.4 of vite-plugin-watch-and-run does not ship with CJs modules at node installation, only esm. Please advise!
Thanks

### Your Example Website or App

Sorry, private repo

### Steps to Reproduce the Bug or Issue

Install latest version through NPM, check installed resources.

### Expected behavior

CJS versions should also be there.

### Platform

Any platform

**Comment by kobleistvan** [comment]
last known functional version: 1.2.1

**Comment by jycouet** [comment]
Do you have an error somewhere? 
How do you see the issue? 

I'm trying to reproduce to then fix it

**Comment by kobleistvan** [comment]
Hi @jycouet ,
Yes, I've been using it with CJS. Up until version 1.2.1, node_modules/vite-plugin-watch-and-run contained esm/index.js and cjs/index.js + cjs/package.json.

Newer versions only installed with /esm.

**Comment by jycouet** [comment]
I stared to look into it, but `svelte-package` doesn't output `cjs` at all. I tried a few alternatives, but didn't get something nice. Maybe I have tto go back to `bob`, but it's less "svelte" way.
Do you have an example of project with cjs?

**Comment by jycouet** [comment]
Hi @kobleistvan , 
Are you still waiting for this?

I don't know if you saw: https://vitejs.dev/guide/migration.html#deprecate-cjs-node-api ?

**Comment by kobleistvan** [comment]
Hi @jycouet ,

Currently we've simply fixed the version to v1.2.1 in order to get the cjs files.
We're having a bit of a hard time upgrading to ESM for the moment, since the vite config files also import some helpers which are just in a CJS format, even though we've seen the deprecation notice.

It will have to do, for now, I suppose :)

**Comment by jycouet** [comment]
I'm sorry to read about this. Yes, ESM & CSJ is a painful journey!
Yeah, it's probably the best to stick with `1.2.1` until then.

I'll close the issue then.
🙏

**Comment by kobleistvan** [comment]
No worries @jycouet, thank you :)

**Comment by jycouet** [comment]
@kobleistvan maybe you wanna check again with the last version? `vite-plugin-watch-and-run@1.4.2`

**Comment by kobleistvan** [comment]
Hi @jycouet ,
Thanks, v142 fixed the issue.

Before:
![v141](https://github.com/jycouet/kitql/assets/6638917/adc221d2-816b-41a8-bd8c-f1dbbc09bf7a)

After:
![v142](https://github.com/jycouet/kitql/assets/6638917/167070d2-3f2d-42fe-8b2d-04dba713cc5e)

🍺

**Comment by kobleistvan** [comment]
There is 1 issue though, I'll make a PR for it, in order to fix this issue:
![error](https://github.com/jycouet/kitql/assets/6638917/25972124-e12d-4aac-92fa-ce2346db3e8a)

**Comment by kobleistvan** [comment]
https://github.com/jycouet/kitql/pull/439
