### ISSUE TITLE
vite-plugin-kit-routes doesn´t handle optional matched params correctly

### ISSUE THREAD

**Issue by xKesvaL** [jycouet/kitql#410]
### Describe the bug

When using the plugin `vite-plugin-kit-routes`, I noticed that when i was using a matched parameter, it wasn´t at all handled properly.
For example, let's take my optional matched parameter lang which i use the `locale` param matcher with, the route then starts with :
`[[lang=locale]]`

In the ROUTES.ts the parameter is then called `lang=locale` which causes issues as you can guess, as the parameter should be called lang. I suggest you look at the given repository so you understand my problem better.

### Your Example Website or App

https://github.com/xKesvaL/kesval.com/tree/refactor

### Steps to Reproduce the Bug or Issue

- Create a new sveltekit project
- Add a route with an optional param
- Add a matcher for this param
- See the routes.ts file bug

### Expected behavior

I expected to have a plain `lang` parameter not following by its matcher.

### Platform

- OS: Linux
- NodeJS: 20.9.0
- vite-plugin-kit-routes@0.0.4

**Comment by jycouet** [comment]
Thx for the report, @all-contributors please add @xKesvaL for detailed report.
I'll fix it in coming hours 👍

**Comment by xKesvaL** [comment]
No problem, love the idea of this library, is why i'm actually putting up these issues :) Thx for your work

**Comment by jycouet** [comment]
Should be fixed in `vite-plugin-kit-routes@0.0.5`, please re open if needed.
