### ISSUE TITLE
vite-plugin-kit-routes doesn´t handle groups properly

### ISSUE THREAD

**Issue by xKesvaL** [jycouet/kitql#411]
### Describe the bug

When using routing groups `(group)` vite-plugin-kit-routes doesn´t handle them properly. Let's take my example : `(assets)/site.webmanifest`
The given key is fine : `assets_site.webmanifest` but what is returned is wrong : `/(assets)/site.webmanifest`
As the group is only used by SvelteKit and is not served, the returned path should be : `/site.webmanifest`

### Your Example Website or App

https://github.com/xKesvaL/kesval.com/tree/refactor

### Steps to Reproduce the Bug or Issue

- Create a new sveltekit project
- Add a grouping folder
- Add a page in this folder
- See the routes.ts file bug

### Expected behavior

I expected to have the path be returned without the group.

### Platform

- OS: Linux
- NodeJS: 20.9.0
- vite-plugin-kit-routes@0.0.4

**Comment by jycouet** [comment]
Thx for the report, @all-contributors please add @xKesvaL for detailed report.
I'll fix it in coming hours 👍

**Comment by jycouet** [comment]
Should be fixed in `vite-plugin-kit-routes@0.0.5`, please re open if needed.

**Comment by ranjan-purbey** [comment]
IMO the key should include the `(group)` part so that `RequestEvent.route.id` values can be used as valid keys for the `route()` function

**Comment by ranjan-purbey** [comment]
My use case is as follows:
I have a tab list in +layout.svelte and need to know which tab is currently active. I was hoping to do something like the following:
```svelte
<script lang="ts">
    import {LayoutRouteId} from "./$types"
    const tabs: Array<{label: string; routeId: LayoutRouteId}> = [...]
</script>

{#each tabs as tab}
    {@const isActive = tab.routeId === $page.route.id}
    {@const link = route(tab.routeId)}
```

I know this is a very niche use-case and isn't a deal-breaker, of course. Though it would be nice if the keys were consistent with route.id

**Comment by jycouet** [comment]
I understand, 

Is this example flying until the end ? 
Here LayoutRouteId contains what ? Multiple ids of all routes under ? What do you do with params ?

Could you do a repro ?

**Comment by ranjan-purbey** [comment]
Yes LayoutRouteId type exported from autogenerated `./$types` file is a string literal type which includes route IDs for all routes in the given layout. I have updated the example in my previous comment. Lmk if a full repro is required
