### ISSUE TITLE
vite-plugin-kit-routes weird path behavior on Windows

### ISSUE THREAD

**Issue by xKesvaL** [jycouet/kitql#415]
### Describe the bug

Note : this is exclusive to windows, I just tested a Linux environment and it worked fine.
When the `ROUTES.ts` file is created, some weird `\` are used for paths. For example :
key : `lang_locale_\about\`
value: `/${params...}\about\${appendSp()}`

You should check out the provided link below to a file that has this problem.

### Your Example Website or App

https://github.com/xKesvaL/kesval.com/blob/refactor/src/lib/ROUTES.ts

### Steps to Reproduce the Bug or Issue

1. Be on windows
2. Create a new SvelteKit project
3. Add any page
4. Start developing with the plugin
5. Issue appears

### Expected behavior

Expected to have normal slashes `/`

### Platform

- OS: **Windows**
- NodeJS: 20.9.0
- vite-plugin-kit-routes@0.0.5

**Comment by xKesvaL** [comment]
By the way, thanks for your quick response on the other 2 issues I put up! It's a great library, and it has big potential I think.

Some other things I thought of but had no idea if they were possible so didn´t file an issue for :
- Custom types for searchParams ?
  - Since i saw that search params were defined using a `Record<string, string>` I thought maybe it's possible to have custom types there for even greater type safety? I don't know how the types would be given to the library though.
- Custom types for routing params
  - Same as the one before basically.

**Comment by jycouet** [comment]
Windows... windows... I'll have a quick look yes 👍.

For the 2 extra questions, yes I have some ideas already for the first one. For the second one, I'm not sure to fully ge it.
You mind chating on Discord? _(I'm jycouet there  as well)_

**Comment by jycouet** [comment]
Should be good now
