### ISSUE TITLE
...Rest parameter routes generate invalid ROUTES

### ISSUE THREAD

**Issue by brandonp-ais** [jycouet/kitql#474]
### Describe the bug

Awesome library!

One issue that may be an issue is the auto-generation for [rest parameter routes](https://kit.svelte.dev/docs/advanced-routing#rest-parameters) that take the form [...my-route].

The auto-generated output has type errors saying "A rest parameter must be of an array type". 

This type error makes it so the remaining file is not autocompletable, and remaining SERVERS and other nice stuff is not available.

### StackBlitz Reproduction

https://stackblitz.com/edit/sveltejs-kit-template-default-iaps3p?file=src%2Flib%2FROUTES.ts

### Steps to Reproduce the Bug or Issue

1. Install this plugin
2. Create a rest parameter route as laid out in the svelte kit docs
3. Start the dev server to generate `ROUTES.ts`

### Expected behavior

I'd expect it to magically have `ROUTES.ts` making typescript happy, although I can imagine this may be a pretty hard problem. 

### Platform

- OS: [Windows]
- NodeJS: [20]
- `@kitql/*` version(s): [0.1.0]

**Comment by jycouet** [comment]
Hoooo, very good point! I don't have these kind of routes (and none of my app testers do apparently 😅)
Thx a lot for trying and writing it here.

I'll come with a fix Soon.

**Comment by jycouet** [comment]
Could you try `vite-plugin-kit-routes@0.1.1-next.1` and let me know what do you think?

**Comment by brandonp-ais** [comment]
That is working perfectly for my actual project, and the repro. Incredible work.

**Comment by jycouet** [comment]
Great to read. Let's spread the world now ^^
