### ISSUE TITLE
Does not work on Node < v20.1.0

### ISSUE THREAD

**Issue by hmnd** [jycouet/kitql#484]
### Describe the bug

Kit Routes fails to generate anything on node versions older than v20.1.0. Instead, an empty `ROUTES.ts` file is generated, with all routes (except top-level pages) ignored).

### Your Example Website or App

n/a

### Steps to Reproduce the Bug or Issue

1. Install node v18
2. Run Kit Routes in any SvelteKit app

### Expected behavior

Kit Routes generates the `ROUTES.ts` file successfully. 

### Platform

- OS: Linux
- NodeJS: 18.1.0
- `@kitql/*` version(s): `vite-plugin-kit-routes` v0.1.1

### Additional context

Kit Routes relies upon the [`recursive` feature of `readdirSync`](https://github.com/jycouet/kitql/blob/6b96616be0128c37dc46b41556c16dfd6c5b3fe8/packages/vite-plugin-kit-routes/src/lib/fs.ts#L31), introduced in Node v20.1.0. This causes the route generation to silently fail on Node versions older than v20.1.0, since `recursive` is ignored and only the top-level files get picked up.

I would recommend adding a minimum node version to the package.json for `vite-plugin-kit-routes` (and probably the other kitql packages), so users don't get confused by an empty ROUTES.ts.

You could also switch to a backward compatible method of reading all the files with `walk` instead, in order to be inline with [SvelteKit's minimum node version of v18](https://github.com/sveltejs/kit/blob/a7f8bdcfabce5cda85dd073a21d0afb6138a7a08/packages/kit/package.json#L98).

**Comment by jycouet** [comment]
Thank you for the detailed info. I recently bump to a newer version of node and didn't see that.

I will inline with `sveltekit` supported version you are right, thx.

**Comment by hmnd** [comment]
Oops, I read the wrong node changelog. `recursive` was _actually_ introduced in v18.17.0, but it turned out I was on v18.16.0 :flushed:. 

So @jycouet I'd say you could safely keep the code as is, just with the explicit node version in package.json :)

**Comment by jycouet** [comment]
I will support `"^16.14 || >=18"` like kit ;)
It's already done 😜

Yes, I added explicit version.

I will bach a few things before publishing ;)

**Comment by jycouet** [comment]
🚀 `vite-plugin-kit-routes@0.1.2` it out. 🚀

Could you try and let me know ?
_I let you close the issue if it's solved 👍_

**Comment by jycouet** [comment]
@all-contributors please add @hmnd for bug
