### ISSUE TITLE
Base path ignored

### ISSUE THREAD

**Issue by hmnd** [jycouet/kitql#485]
### Describe the bug

Kit Routes does not prefix generated paths with `kit.paths.base`.

### Your Example Website or App

https://stackblitz.com/edit/sveltejs-kit-template-default-oojpga?file=src%2Flib%2FROUTES.ts

### Steps to Reproduce the Bug or Issue

1. Configure a custom `kit.paths.base` in `svelte.config.js`
2. Attempt to use a route from `ROUTES.ts`

### Expected behavior

Generated route is prefixed with the configured base path.

### Platform

- OS: Linux
- NodeJS: 20.10.0
- `@kitql/*` version(s): `vite-plugin-kit-routes` v0.1.1

### Additional context

Prior to this plugin, I would usually handle this with a wrapper around SvelteKit's `resolvePath` method, which would prefix the base to the path generated by `resolvePath`.

However, because the plugin doesn't get access to `$app/paths`, I fear the only way to fix this would be to either parse the svelte.config.js or (more simply or temporarily) allow the user to provide their own base path to the plugin directly.

**Comment by jycouet** [comment]
I learn so much with all these age cases. Thx for reporting. 🙏

**Comment by jycouet** [comment]
🚀 `vite-plugin-kit-routes@0.1.2` it out. 🚀

Could you try and let me know ?
_I let you close the issue if it's solved 👍_

**Comment by hmnd** [comment]
@jycouet thanks for the super quick fix! It works great!

I would actually suggest going a step further and always prefixing with `base`, since it is guaranteed to either be a `/` prefixed string or empty. No need for extra config from users that way either!

**Comment by jycouet** [comment]
I hesitated a lot ☺️

I the end, I decided to go with the option thinking that it's less code to the browser if you don't have base.

Ideally I would read the config... I started it... But was lazy 😜. I think that the bool is good enough for now 👍
