### ISSUE TITLE
Actions not recognized

### ISSUE THREAD

**Issue by tmarnet** [jycouet/kitql#491]
### Describe the bug

Me again 👋 

None of the actions in my Sveltekit project are being recognized and thus their route not generated in the `ACTIONS` object/type.

This seems to be working fine if I manually type them using `satifies Actions`, but since I'm relying on the automatic typings for both my load/actions (can't remember if its their official VS Code extension that provides this, or something else, but it's definitely part of SvelteKit) it's not really working.

### Your Example Website or App

https://stackblitz.com/edit/github-ev4sed?file=src%2Flib%2FROUTES.ts

### Steps to Reproduce the Bug or Issue

1. Starting from the [template](https://stackblitz.com/github.com/jycouet/kitql/tree/main/packages/create-kitql/templates/kit-routes)
2. Create a `/with-satisfies/+page.server.ts` file with the following content:
```ts
import type { Actions } from './$types'

export const actions = {
	action1: () => {},
	action2() {},
	action3: async () => {},
	async action4() {}
} satisfies Actions;
```
3. Create a `/without-satisfies/+page.server.ts` file with the following content:
```ts
export const actions = {
	action1: () => {},
	action2() {},
	action3: async () => {},
	async action4() {}
};
```
4. Open the `ROUTES.ts` file and notice the `/without-satisfies` actions routes aren't in there:
```ts
export const ACTIONS = {
	'/with-satisfies': (action: 'action1' | 'action2' | 'action3' | 'action4') => {
		return `/with-satisfies?/${action}`;
	}
};
```

### Expected behavior

Actions that are not manually typed using `statisfies Actions` should be correctly recognized and their route generated.

### Platform

- OS: macOS
- NodeJS: 20.10.0
- `vite-plugin-kit-routes`: 0.1.2

**Comment by jycouet** [comment]
Hooo, I know what you mean. It's svelte LSP making this "typing without typing" ^^.
Great catch 🙏

I'll do that later 👍

**Comment by jycouet** [comment]
@all-contributors please add @tmarnet for bug

**Comment by jycouet** [comment]
🚀 `vite-plugin-kit-routes@0.1.3` it out. 🚀

Could you try and let me know ?
_I let you close the issue if it's solved 👍_

**Comment by tmarnet** [comment]
Working fine with `vite-plugin-kit-routes@0.1.3`, thanks!

Closing this issue.
