### ISSUE TITLE
Actions search params not working

### ISSUE THREAD

**Issue by tmarnet** [jycouet/kitql#496]
### Describe the bug

Configuring and using search params on actions currently doesn't work properly because we're appending the `?` character at the begining of the search params, but actions paths already include this `?`, so in that case we should be using `&` instead.

### Your Example Website or App

https://stackblitz.com/edit/github-nxv4s3

### Steps to Reproduce the Bug or Issue

1. Starting from the [template](https://stackblitz.com/github.com/jycouet/kitql/tree/main/packages/create-kitql/templates/kit-routes)
2. Create a `/about/+page.server.ts` file with the following content:
```ts
import type { Actions } from './$types'

export const actions = {
	withSearchParam(event) {
		console.log('Received redirectUrl', event.url.searchParams.get('redirectUrl'));
	}
} satisfies Actions;
```
3. In the `/about/+page.svelte` paste the following content:
```ts
<script lang="ts">
  import { enhance } from '$app/forms';
  import { page } from '$app/stores';
  import { ACTIONS } from '$lib/ROUTES';
</script>

<h2>About</h2>

<p>Yes, you are on the about page.</p>

<form
  use:enhance
  method="POST"
  action={ACTIONS['/about']('withSearchParam', { redirectUrl: $page.url.pathname })}
>
  <button>
    Go!
  </button>
</form>
```
4. Update the `kitRoutes` with the following:
```ts
ACTIONS: {
	auth: {
		explicit_search_params: {
			redirectUrl: {
				required: true,
				type: 'string',
			},
		},
	},
},
```
5. Run the app, inspect the `Go!` button form on the `/about` page and notice that the form action equals `/about?/withSearchParam?redirectUrl=%2Fabout` when it should in reality be `/about?/withSearchParam&redirectUrl=%2Fabout`.

### Expected behavior

When appending search params to an action we should use the `&` character instead of the `?` character.

### Platform

- OS: macOS
- NodeJS: 20.10.0
- `vite-plugin-kit-routes`: 0.1.3

**Comment by jycouet** [comment]
I guess that this is applicable only to named action?

You rock, by finding all this 🎉

**Comment by tmarnet** [comment]
I updated the Stackblitz to include a default action as well.

It looks like this is broken for both default and named actions since the plugin treats default actions as named ones (by appending `/default`):

<img width="577" alt="Screenshot 2023-11-25 at 12 16 36" src="https://github.com/jycouet/kitql/assets/10536410/3e591481-6f86-43e8-b20f-b864e09a625a">

**Comment by jycouet** [comment]
I almost feels embarrassed! lol.
I'll fix this soon 👍

**Comment by tmarnet** [comment]
Let me rectify my previous comment:

1. If, for a given page, there is only a default action, then `appendSp` works fine, see this new Stackblitz: https://stackblitz.com/edit/github-b9auqn
2. But if there is also a named action, then the plugin treats the default action as a named one, hence `appendSp` doesn't behave properly

**Comment by jycouet** [comment]
Hooo, but you can't have a named & default at the same time?!

https://kit.svelte.dev/docs/form-actions#named-actions
![Capture d’écran 2023-11-25 à 18 32 50](https://github.com/jycouet/kitql/assets/5312607/741dfeee-6be1-4f1d-b748-bf62af6a6b90)

Anyway, I'll fix the SearchParam stuff 👍

**Comment by tmarnet** [comment]
Didn't know that, TIL!

Thanks 🙂

**Comment by jycouet** [comment]
Hooo, you get a warning, only when you start using it: 
```
Error: When using named actions, the default action cannot be used. See the docs for more info: https://kit.svelte.dev/docs/form-actions#named-actions
```

I guess that I can put the warning directly directly when I see this 

CoooooooL stuff

**Comment by jycouet** [comment]
Héhéhé, new log coming:

![Capture d’écran 2023-11-25 à 18 55 34](https://github.com/jycouet/kitql/assets/5312607/7972d4ef-46e2-4afc-908f-a34174a28482)

**Comment by jycouet** [comment]
🚀 `vite-plugin-kit-routes@0.1.4` it out. 🚀

Could you try and let me know ?
_I let you close the issue if it's solved 👍_

**Comment by jycouet** [comment]
Thx to you I even can put out more content: https://x.com/jycouet/status/1728489740184248599?s=20 😅

🙏 🙏 🙏

**Comment by tmarnet** [comment]
Awesome!

It's working fine with `vite-plugin-kit-routes@0.1.4`, thanks!

Closing this issue.
