### ISSUE TITLE
kit-routes - Root path does not contain a `/`

### ISSUE THREAD

**Issue by xKesvaL** [jycouet/kitql#527]
### Describe the bug

When calling `route('/')` it returns an empty path instead of `/`

### Severity

serious, but I can work around it

### Steps to Reproduce the Bug

[Repo where this happens](https://github.com/xKesvaL/leetstrength)
This happens in the `apps/app` folder
I can't explain how to reproduce this as I don't know what causes it, but It might be because of the group.

**Comment by jycouet** [comment]
Hooo, it's because of https://github.com/xKesvaL/leetstrength/blob/main/apps/app/vite.config.ts#L14C10-L14C10

I'll look into this 👀

**Comment by jycouet** [comment]
🚀 `vite-plugin-kit-routes@0.2.3` it out. 🚀

Could you try and let me know ?
_I let you close the issue if it's solved 👍_
