### ISSUE TITLE
vite-plugin-striper + remult + @BackendMethod decorator on entity - shows errors

### ISSUE THREAD

**Issue by mihaa1** [jycouet/kitql#539]
### Describe the bug

Reproduce:
* add vite-plugin-striper
* add entity backend method with decorator @BackendMethod
* on entity - use Allow, Validtor import from remult
* browser shows errors:
```
Uncaught ReferenceError: Validators is not defined
Uncaught ReferenceError: Allow is not defined
```

Code: 
Entity:
```
import { Allow, BackendMethod, Entity, Fields, Validators } from 'remult'

@Entity<User2>('userstest', {
	allowApiCrud: Allow.authenticated,
})
export class User2 {
	@Fields.uuid()
	id = ''

	@Fields.string({
		validate: [Validators.required, Validators.uniqueOnBackend],
	})
	email = ''

	@BackendMethod({ allowed: Allow.everyone })
	async testMethod() {
		console.log('hello')
	}
}
```

vite.config.ts
```
import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'
import { striper } from 'vite-plugin-striper'

// https://vitejs.dev/config/
export default defineConfig({
	plugins: [striper({ decorators: ['BackendMethod'] }), react()],
	server: { proxy: { '/api': 'http://localhost:3002' } },
})
```

### Severity

serious, but I can work around it

### Steps to Reproduce the Bug

Reproduce:
* add vite-plugin-striper
* add entity backend method with decorator @BackendMethod
* on entity - use Allow, Validtor import from remult
* browser shows errors:
```
Uncaught ReferenceError: Validators is not defined
Uncaught ReferenceError: Allow is not defined
```

**Comment by jycouet** [comment]
Thx for reporting, I'll have a look later today

**Comment by jycouet** [comment]
@all-contributors please add @mihaa1 for bug

**Comment by jycouet** [comment]
🚀 `vite-plugin-striper@0.0.7` it out. 🚀

Could you try and let me know ?
_I let you close the issue if it's solved 👍_

**Comment by mihaa1** [comment]
Thanks for the quick fix.
I'm getting a weird error with 0.08. I was using 0.04, and all versions above that give me this:
```
failed to load config from /Users/vite.config.ts
error when starting dev server:
TypeError: (0 , import_vite_plugin_watch_and_run.default) is not a function
```

Checking with u before I start to dig further

**Comment by jycouet** [comment]
Thx for the quick notice, I'll have a look right now.

**Comment by jycouet** [comment]
Let's chat here: https://discord.com/channels/975754286384418847/1183356577835647086/1183830630090420296

**Comment by jycouet** [comment]
🚀 `vite-plugin-striper@0.1.4` it out. 🚀

Could you try and let me know ?
_I let you close the issue if it's solved 👍_

**Comment by mihaa1** [comment]
Works, thanks!
