### ISSUE TITLE
kit-routes: Server endpoints are no longer recognized when in `export function` style

### ISSUE THREAD

**Issue by Dan1ve** [jycouet/kitql#560]
### Describe the bug

Updating kit-routes from `v0.1.4` to `v0.2.10`  results in an empty `SERVERS` member in the generated `ROUTES.ts`.

This is a regression (it was working in the old version).

I believe this happens because the plugin only recognizes methods written in  "lambda style":

*Working*:
``` ts
// server.ts
export const GET = async () => {
... 
}
```

*No longer working*:
``` ts
// server.ts
export async function GET() {
... 
}
```

### Severity

serious, but I can work around it

### Steps to Reproduce the Bug

1. Use the plugin with a SvelteKit app that has the following route:  `src/routes/foo/+server.ts`
2.  Add the following to `+server.ts` : 

``` ts
export async function GET() {
 return new Response();
}
```

3. Note that the plugin doesn't add the endpoint to the generated  `SERVERS` entry.

**Comment by jycouet** [comment]
Thx for reporting, I had an issue with the last deploy. I'll have a look RN

**Comment by jycouet** [comment]
@all-contributors please add @Dan1ve for bug

**Comment by jycouet** [comment]
🚀 `vite-plugin-kit-routes@0.2.11` it out. 🚀

Could you try and let me know ?
_I let you close the issue if it's solved 👍_

**Comment by Dan1ve** [comment]
Pretty amazing response time, thanks a lot. Fixed indeed :+1:
