### ISSUE TITLE
Vite-Plugin-Kit-Route for svelte

### ISSUE THREAD

**Issue by JonathonRP** [jycouet/kitql#579]
**Is your feature request related to a problem? Please describe.**

Vite-Plugin-Kit-Route only reads from routes folder in src which does not exist for just svelte and non-kit projects.

**Describe the solution you'd like**

ability to have routes or specify routes that exist in location other than kit based (file base) routes.

**Describe alternatives you've considered**

separate project for non-kit projects or ability in current project to have routes specified in js/ts files that map to components.

**Additional context**

currently using svelte-pathfinder for routing

**Comment by jycouet** [comment]
Even more strict, it's reading only from `src/routes`. It's also detecting a route via special files: `+page.svelte` / `+page.server.ts` / `+server.ts`.

I'm not sure how easy/hard is to adapt to your specific use-case.
As the name suggest, this lib is for 'kit'.

I'll close with "not planned". If you want to speak more about it, do not hesitate to contact me and/or reopen.
