### ISSUE TITLE
Option to match `$page.route.id`?

### ISSUE THREAD

**Issue by jycouet** [jycouet/kitql#625]
My use case is as follows:
I have a tab list in +layout.svelte and need to know which tab is currently active. I was hoping to do something like the following:
```svelte
<script lang="ts">
    import type {LayoutRouteId} from "./$types"
    import {page} from "$app/stores"
    const tabs: Array<{label: string; routeId: LayoutRouteId}> = [
        {"label": "Tab 1", routeId: "/a/(groupA)/b"},
        ...
    ]
</script>

{#each tabs as tab}
    {@const isActive = tab.routeId === $page.route.id}
    {@const link = route(tab.routeId)}
   <a href={link} class:active={isActive}>{tab.label}</a>
{/each}
<slot/>
```

I know this is a very niche use-case and isn't a deal-breaker, of course. Though it would be nice if the keys were consistent with route.id

_Originally posted by @ranjan-purbey in https://github.com/jycouet/kitql/issues/411#issuecomment-1954892686_

**Comment by jycouet** [comment]
I created the issue here @ranjan-purbey to track it down.

We would need to have also optional param, like: `"/[[lang]]/gp/(logged)/one"`

What do you think about a flag to have this?

**Comment by ranjan-purbey** [comment]
Thanks @jycouet ! Yes I think in order to avoid breaking changes, a flag makes sense. And yes it should include both optional and rest (not sure if it already does) parameters.

**Comment by jycouet** [comment]
Today, I put params but not optional params. The idea was to avoid long strings, even type checked.

Let's try the `flag` idea and we what people prefer for `1.0`.

**Comment by ranjan-purbey** [comment]
Thanks @jycouet! This is perfect!
