### ISSUE TITLE
🚸 IMPROVE: kitQL codegen - Provide (generic?) type for stores

### ISSUE THREAD

**Issue by jbruxelle** [jycouet/kitql#63]
#### Package graphql-codegen

  - [ ] KQL stores should maybe have a type (ideally generic).

   Example: 
  * with Sveltekit I can pass a store as a param, e.g a Writable<T>
  * when it comes to a KQL custom store, i have no type to provide.

     ```
    export const storyblok = (node: HTMLElement, storyStore: KQLStore<PageDetailFragment>) => { 
        // I do things here including using storyStore.patch
    }
      ```

**Comment by jycouet** [comment]
Nice one 👍
Will you work on it? 🙃

**Comment by jbruxelle** [comment]
I was having a look but i'm not familiar with codegen... 😄 Just have to figure out where i can get the return type of a query document... 🤔

**Comment by jycouet** [comment]
🙃 I let you have fun with `console.log` a bit then 😂

**Comment by jycouet** [comment]
What about
```ts
function myCoolFunction(store: typeof KQL_AllContinents) {
	store.resetCache();
}
```

😯

**Comment by jbruxelle** [comment]
Works fines using typeof, I do not need more since this is for a very specific usage. 🎉
