### ISSUE TITLE
Parameters<typeof path> Windows \ escaping

### ISSUE THREAD

**Issue by PudottaPommin** [jycouet/kitql#643]
### Describe the bug

When on windows, I get parameter type like `Parameters<typeof import('..\..\params/locale.ts').match>[0]`, which causes type error `Cannot find module '....params/locale.ts' or its corresponding type declarations`.

Fix should be easy enough, which is to change [L686](https://github.com/jycouet/kitql/blob/main/packages/vite-plugin-kit-routes/src/lib/plugin.ts#L686) to `posix.relative`. I can create PR, but file is using `relative` from `@kit/internals`, so I'm not sure, if it's better to change just `plugin.ts` or do change inside `@kit/internals`.

### Severity

annoyance

### Steps to Reproduce the Bug

1. install `vite-plugin-kit-routes` on windows
2. use param matcher in route
3. open ROUTES.ts

**Comment by jycouet** [comment]
Hello, 
Thx for reporting & well spotted.

What do you think about exporting `posixRelative` from `@kitql/internals` ?

I can probably do it in a few hours, but if you wanna do it... it's perfect for me too 👍
When I have time and I will start, I'll look here to see if you want to do the PR or not. (I'll write here)

**Comment by jycouet** [comment]
Nahhh, `posix` is already here... Let's use it directly! I'll do it now

**Comment by jycouet** [comment]
Should be available in `vite-plugin-kit-routes@0.6.2`
I let you close the issue if this one is fixed.
Thx for your help

**Comment by PudottaPommin** [comment]
thanks! @jycouet it's working like a charm
