### ISSUE TITLE
`vite-plugin-kit-routes` ignores `js` files

### ISSUE THREAD

**Issue by ryoppippi** [jycouet/kitql#660]
### Describe the bug

When I create server endpoint with `+server.js`, that files ignores and type errors occur when using `route` function.

### Severity

serious, but I can work around it

### Steps to Reproduce the Bug

1. `bun create svelte` and create with js/jsdoc
2. following the setup of `vite-plugin-kit-routes` docs
3. `bun run dev`
4. We can't see the type definition of the endpoints with `js` files

**Comment by jycouet** [comment]
Yes, today this plugin is working exclusivly in typescript. I didn't plan a js version for now.

**Comment by ryoppippi** [comment]
OK, then please add that information to README
