### ISSUE TITLE
Allow import of 'AllObjs' which contains all routes

### ISSUE THREAD

**Issue by duducpp** [jycouet/kitql#675]
**Is your feature request related to a problem? Please describe.**

In my project users can create pages with a custom alias. I need to avoid alias of pre-existing routes.

**Describe the solution you'd like**

Make `AllObjs` exportable, so I can parse it and check if the route already exists before allowing the new page alias to be created.

**Comment by jycouet** [comment]
Should be fixed in `vite-plugin-kit-routes@0.6.3`, please re open if needed.
Thanks for your work
