### ISSUE TITLE
Unused Local Variable StringOrUndefined from vite-plugin-kit-routes

### ISSUE THREAD

**Issue by johnathanludwig** [jycouet/kitql#681]
### Describe the bug

When typescript has `noUnusedLocals` set to true, the routes file generated has one compiler error about `StringOrUndefined`.

Its not possible to disable the error for this case as the file will be regenerated so the only way is to allow unused locals.

```
====================================
Loading svelte-check in workspace: /home/projects/sveltejs-kit-template-default-brqvq1
Getting Svelte diagnostics...

/home/projects/sveltejs-kit-template-default-brqvq1/src/lib/ROUTES.ts:86:10
Error: 'StringOrUndefined' is declared but its value is never read. 

function StringOrUndefined(val: any) {
  if (val === undefined) {

====================================
svelte-check found 1 error and 0 warnings in 1 file
```

### Severity

annoyance

### Steps to Reproduce the Bug

1. Update jsconfig.json or tsconfig.json and set `"noUnusedLocals": true`
2. Run the sveltekit `check` script.

In the reproduction URL you can just run `npm run check` to see the error.

### Reproduction

https://stackblitz.com/edit/sveltejs-kit-template-default-brqvq1?file=svelte.config.js

**Comment by jycouet** [comment]
Hi,
Thank you for reporting it.

I have to think how to solve this... Will tackle this in a few hours 🤞

**Comment by jycouet** [comment]
@all-contributors please add @johnathanludwig for bug
