### ISSUE TITLE
Updating to 6.4.0 causes `svelte-check` to fail due to `@ts-expect-error`

### ISSUE THREAD

**Issue by Dan1ve** [jycouet/kitql#686]
### Describe the bug

I updated from v6.2.0 to v6.4.0, which re-generated the `ROUTES.ts` file.

Running `svelte-check` now produces a TypeScript error for the generated file at the `StringOrUndefined` helper function that wasn't being raised before:
 
```
Error: Unused '@ts-expect-error' directive. 

// @ts-expect-error can break noUnusedLocals ts rule
function StringOrUndefined(val: any) {
```

It's also visible in VS Code:

![image](https://github.com/user-attachments/assets/c0286e57-0d1f-455b-aa82-78028824f220)

As this file is generated, I cannot fix this myself. 

I'm not an expert on TypeScript error suppression, but maybe `@ts-ignore` would work instead? 

### Severity

blocking an upgrade

### Steps to Reproduce the Bug

1. Setup a simple SvelteKit project with at least one route
2. Run the generating step. If relevant, I use 

```
kitRoutes({
	generated_file_path: 'src/lib/generated/ROUTES.ts'
}) 
```

3. Run `svelte-check --threshold error`
4. You'll see the error above

**Comment by jycouet** [comment]
Hummm... It depend on another ticket (I'll link later)
My fix was probably not the best...

I'll look later.
