### ISSUE TITLE
Compatibility with Svelte 5

### ISSUE THREAD

**Issue by garysassano** [jycouet/kitql#696]
I get the following warning when installing:

![image](https://github.com/user-attachments/assets/bad59458-d91c-465e-8269-b5c6e8ffd54d)

**Comment by jycouet** [comment]
Should be no issue. 

I'll fix the peer deps requirement as soon as I have a laptop back (a few days)

Thx for reporting

**Comment by jycouet** [comment]
I'm back at my laptop, and I'm cleaning issues.
Acutually, this is not linked with `vite-plugin-kit-routes` at all.

The warning is coming from `@sveltejs/vite-plugin-svelte`. With Svelte `5+`, you should try `"@sveltejs/vite-plugin-svelte": "^4.0.0-next.6",`.

I'm closing this issue as I can't do anyhing here. Feel free to re open with a comment if I missed something.

**Comment by johnathanludwig** [comment]
With svelte 5 just released I am trying the upgrade, but still seeing svelte 4.2.19 installed. According to `pnpm why` it looks like it is due to `@kitql/internals`. Could this be reopened and @kitql updated to support v5?

```
vite-plugin-kit-routes 0.6.11
└─┬ @kitql/internals 0.9.10
  └── svelte 4.2.19
```

**Comment by jycouet** [comment]
As it's an internal dep of `vite-plugin-kit-routes` > `@kitql/internals` it should not be an issue in your side.
You are facing something strange?

FYI, I will bump it soon.

**Comment by johnathanludwig** [comment]
No issue, just noticed it was keeping a copy of Svelte 4 around from this. I used resolutions to force it to 5 and things are still working.

**Comment by jycouet** [comment]
@johnathanludwig could you look at `vite-plugin-kit-routes@0.7.0-next.1` and see if it's solving your force issue ?

(I re open the issue just to track it, it's it's solve please close it ;))

**Comment by fnimick** [comment]
(fyi, @kitql/handles also needs a peer dep version bump)

**Comment by jycouet** [comment]
Can you check with `@kitql/handles@0.2.1-next.0` ?

**Comment by johnathanludwig** [comment]
Sorry for the delay, I forgot about this last week.

Just tried next.1 and it seems good.

```
vite-plugin-kit-routes 0.7.0-next.1
├─┬ @kitql/internals 0.10.0-next.1
│ └── svelte 5.1.1
└─┬ @sveltejs/kit 2.7.2 peer
  ├─┬ @sveltejs/vite-plugin-svelte 4.0.0 peer
  │ ├─┬ @sveltejs/vite-plugin-svelte-inspector 3.0.1
  │ │ └── svelte 5.1.1 peer
  │ └── svelte 5.1.1 peer
  └── svelte 5.1.1 peer
```
