### ISSUE TITLE
Respect SvelteKit’s `trailingSlash = 'always'` behavior

### ISSUE THREAD

**Issue by jycouet** [jycouet/kitql#698]
### Discussed in https://github.com/jycouet/kitql/discussions/693

<div type='discussions-op-text'>

<sup>Originally posted by **danieljb** August  4, 2024</sup>
Hi, I’ve set up kitql in a project configured to use [trailing slashes](https://kit.svelte.dev/docs/page-options#trailingslash) via export in a `+layout.ts` file.

This generally works, but the links generated by kitql are missing the trailing slash. This can lead to an additional request when SvelteKit redirects to the with-trailing-slash url path, e.g. a link to `/about` will be redirected to `/about/`.

I tried adding the trailing slash to kitql’s route call, e.g. `route('/about/')` but this results in a type error. Is there a way to configure kitql to accept the trailing slash behavior? </div>

**Comment by jycouet** [comment]
> A global config flag would definitely work in my case. Fully agree this would be a good first step.

**Comment by jycouet** [comment]
Hi @danieljb
It should be done in `vite-plugin-kit-routes@0.6.6`, please re open if needed.
Let me know

**Comment by danieljb** [comment]
Amazing, thanks a lot for the fast response and implementation. Very excited to check it out. Will let you know if anything comes up.
