### ISSUE TITLE
Readme driven development

### ISSUE THREAD

**Issue by frederikhors** [jycouet/kitql#71]
Dear @jycouet,

I like your issues backlog and I like this project as you already know.

But a few minutes ago I was in need to find some docs and found nothing.

Can I suggest you this method? https://tom.preston-werner.com/2010/08/23/readme-driven-development.html

:smile:

I can help to write markdowns.

**Comment by jycouet** [comment]
It's what I wrote here: https://twitter.com/jycouet/status/1496917913831280640?s=20&t=eNelBIA5jZf_NGuKpZKZVQ 😇
You can already start in the folder: `website/doc` and create a PR 👌

**Comment by frederikhors** [comment]
Oh wow. I didn’t know that. We think the same! I will help ASAP.
