### ISSUE TITLE
Micromatch dependency - Security advisory `vite-plugin-watch-and-run `

### ISSUE THREAD

**Issue by lb-** [jycouet/kitql#716]
### Describe the bug

When installing `vite-plugin-watch-and-run` we get a security vulnerability advisory.

```
# npm audit report

micromatch  <4.0.8
Severity: moderate
Regular Expression Denial of Service (ReDoS) in micromatch - https://github.com/advisories/GHSA-952p-6rrq-rcjv
No fix available
node_modules/micromatch
node_modules/vite-plugin-watch-and-run/node_modules/micromatch
  vite-plugin-watch-and-run  *
  Depends on vulnerable versions of micromatch
  node_modules/vite-plugin-watch-and-run

2 moderate severity vulnerabilities

Some issues need review, and may require choosing
a different dependency.
```

### Severity

annoyance

### Steps to Reproduce the Bug

1. `npm install vite-plugin-watch-and-run`
2. Observe npm audit warning `2 moderate severity vulnerabilities`

**Comment by lb-** [comment]
https://github.com/jycouet/kitql/blob/53804e44e6ae3ba8e0de54a2de87cae4f4e32437/packages/vite-plugin-watch-and-run/package.json#L47

Updating this line to `4.0.8` should fix the issue.

See https://github.com/advisories/GHSA-952p-6rrq-rcjv

**Comment by jycouet** [comment]
Thx for reporting.
I will do this today.

**Comment by lb-** [comment]
Thank you
