### ISSUE TITLE
No query function inside /_kitql/graphqlStores.ts

### ISSUE THREAD

**Issue by halindraprakoso** [jycouet/kitql#73]
Hi, this library looks promising. However, I'm having an issue.
I have a GetUser query, then I ran the `gen` script, but graphql-codegen does not generate the query inside `.../_kitql/graphqlStores.ts`. There is only KQL_GetUsers. Am I missing something?

**Comment by halindraprakoso** [comment]
oh I figured it out. I was referencing the youtube video. I see that now it should be using `.query`

Another Q though, can I remove the KQL prefix? removed it in the yaml file but it's still there

**Comment by jycouet** [comment]
Yes, the video is outdated. But with the '.query' we have less imports. It's better 👍

Good catch for the prefix. If you remove it it goes to default 'KQL_'. What you would like is: no prefix?

**Comment by jycouet** [comment]
Did you try prefix:""?
I like to have a prefix to find all graphql easily 😜

I'll try all this later today

**Comment by halindraprakoso** [comment]
> Yes, the video is outdated. But with the '.query' we have less imports. It's better 👍

Agreed . it's more compact than the previous approach.

> Good catch for the prefix. If you remove it it goes to default 'KQL_'. What you would like is: no prefix?

Now that I think about it, it's certainly better with prefix. Thank you!

**Comment by jycouet** [comment]
@halindraprakoso great that you find it better with prefix too 👍
I'm curious, did you choose `KQL_` as well? or did you find something else?

FYI, I added new tests
- [x] `operationPrefix` not set in the config file => `KQL_xxx`
- [x] `operationPrefix: "HELLO_YOU"` => `HELLO_YOUxxx`
- [x] `operationPrefix: ""` => `xxx`

**Comment by halindraprakoso** [comment]
I'm leaving it as is. KQL is nice for intellisense 👍

Is subscription already supported?

**Comment by jycouet** [comment]
Not yet 😉
