### ISSUE TITLE
Babel parser causes an ssr error

### ISSUE THREAD

**Issue by olehmisar** [jycouet/kitql#758]
### Describe the bug

i got this error:
```
{
  code: 'BABEL_PARSER_SYNTAX_ERROR',
  reasonCode: 'UnexpectedReservedWord',
  loc: Position { line: 23, column: 20, index: 743 },
  pos: 743,
  syntaxPlugin: undefined
}
```

### Severity

blocking all usage of KitQL

### Steps to Reproduce the Bug

i am too busy

**Comment by jycouet** [comment]
Hello,
Could you explain a little little more ?
First, I don't even know what package are you using in KitQL ?! What version ?!

I understand that everyone is busy 🙃

**Comment by olehmisar** [comment]
i am using `vite-plugin-kit-routes`. I guess it happens because i am importing a dependency that has a top-level await. I import it in `export function POST()` in a `+server.ts` file

**Comment by jycouet** [comment]
Okay, I'll try to reproduce in coming days.

**Comment by jycouet** [comment]
I spent time this morning... did a few tests... with top level await, with import lib... I don't have any error!
Could you share your file where you have this error?

**Comment by jycouet** [comment]
What should we do here ?

**Comment by olehmisar** [comment]
Idk, it was a throwaway project anyway. I never saw this error in any other of my projects that I use with kit routes plugin. You can probably close this (nonsense) issue.
