### ISSUE TITLE
@kitql/handles depends on @kitql/helpers but does not specify it as either a dependency or peer dependency

### ISSUE THREAD

**Issue by fnimick** [jycouet/kitql#789]
### Describe the bug

Version: 0.2.1

Fails at runtime with `Error: Cannot find module '@kitql/helpers' imported from '.../node_modules/@kitql/handles/esm/hooks/handle-proxies.js'

### Severity

annoyance

### Steps to Reproduce the Bug

Install and import @kitql/handles@0.2.1

**Comment by jycouet** [comment]
Thank you for reporting. I'll fix it now

**Comment by jycouet** [comment]
Let me know if it's better in `@kitql/handles@0.2.2` and reopen if it's not the case.

**Comment by fnimick** [comment]
confirmed fixed - thank you!
