### ISSUE TITLE
Links broken for create-kitQL

### ISSUE THREAD

**Issue by s-petey** [jycouet/kitql#820]
### Describe the bug

Reading through the [docs](https://www.kitql.dev/docs/create) then opening any of the online versions errors. 

On the main readme there is a link to `https://github.com/jycouet/kitql/blob/main/packages/create-kitql/README.md` which is a dead link.

### Severity

annoyance

### Steps to Reproduce the Bug

1. Go to the docs website https://www.kitql.dev/docs/create
2. Click on any of the "Online" templates

1. Go to the github [readme](https://github.com/jycouet/kitql?tab=readme-ov-file#-infos)
2. Click on the link for [create-kitql](https://github.com/jycouet/kitql/blob/main/packages/create-kitql/README.md)

**Comment by jycouet** [comment]
Thank you for reporting.
Yes, `create-kitql` should be removed, I use all my best practices in `npm create remult@latest` _(sveltekit template)_.
I'll update the doc later
