### ISSUE TITLE
Blank lines in KitQLInfo

### ISSUE THREAD

**Issue by frederikhors** [jycouet/kitql#89]
I'm trying KitQLInfo on my WIndows 10 Chrome 99:

![image](https://user-images.githubusercontent.com/41120635/160024366-97b4f5c2-f684-4fd0-9487-ba615ff4db38.png)

Do you see the blank lines in select?

**Comment by jycouet** [comment]
It's because it's sensitive data 😅

More serious, I had this also yesterday, I have to check why! (Maybe a CSS S**** issue 🙃)

**Comment by jycouet** [comment]
Hoooo, I know, it's because of tailwindcss!
I'm not sure how to address that. It's the reset that is doing this I think.

But I don't know what property to set to have it right :o with or without tailwindcss.

**Comment by frederikhors** [comment]
I'll remove Tailwind ASAP.

**Comment by jycouet** [comment]
It's fixed.
It will work also with tailwind now 👍
